# Generated by Django 4.2.2 on 2025-09-11 17:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('router_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(default='ConnectWise_Guest', max_length=32)),
                ('password', models.CharField(blank=True, max_length=64)),
                ('enabled', models.BooleanField(default=False)),
                ('bandwidth_limit', models.PositiveIntegerField(default=10, help_text='Bandwidth limit in Mbps')),
                ('access_duration', models.PositiveIntegerField(default=24, help_text='Access duration in hours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RouterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('config_change', 'Configuration Change'), ('reboot', 'Router Reboot'), ('firmware_update', 'Firmware Update'), ('security_event', 'Security Event'), ('connection', 'Connection Event')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='connecteddevice',
            options={'ordering': ['-last_seen']},
        ),
        migrations.AlterModelOptions(
            name='router',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='connecteddevice',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='connecteddevice',
            name='connection_type',
            field=models.CharField(choices=[('wired', 'Wired'), ('wireless_2.4', 'Wireless (2.4 GHz)'), ('wireless_5', 'Wireless (5 GHz)'), ('guest', 'Guest Network')], default='wireless_2.4', max_length=15),
        ),
        migrations.AddField(
            model_name='connecteddevice',
            name='data_usage',
            field=models.BigIntegerField(default=0, help_text='Data usage in bytes'),
        ),
        migrations.AddField(
            model_name='connecteddevice',
            name='device_type',
            field=models.CharField(choices=[('computer', 'Computer'), ('phone', 'Phone'), ('tablet', 'Tablet'), ('tv', 'TV'), ('game_console', 'Game Console'), ('iot', 'IoT Device'), ('other', 'Other')], default='other', max_length=15),
        ),
        migrations.AddField(
            model_name='connecteddevice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='connecteddevice',
            name='signal_strength',
            field=models.IntegerField(blank=True, help_text='Signal strength in dBm (0 to -100)', null=True, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='router',
            name='band',
            field=models.CharField(choices=[('2.4ghz', '2.4 GHz (Longer range)'), ('5ghz', '5 GHz (Faster speed)'), ('both', 'Both (Dual-band)')], default='both', max_length=10),
        ),
        migrations.AddField(
            model_name='router',
            name='channel_width',
            field=models.CharField(choices=[('20mhz', '20 MHz'), ('40mhz', '40 MHz'), ('80mhz', '80 MHz'), ('auto', 'Auto (Recommended)')], default='auto', max_length=10),
        ),
        migrations.AddField(
            model_name='router',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='router',
            name='firewall_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='router',
            name='hide_ssid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='router',
            name='remote_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='router',
            name='security_type',
            field=models.CharField(choices=[('wpa2', 'WPA2-Personal (Recommended)'), ('wpa3', 'WPA3-Personal'), ('wpa', 'WPA/WPA2-Personal'), ('wep', 'WEP (Insecure)'), ('none', 'None (Open Network)')], default='wpa2', max_length=10),
        ),
        migrations.AddField(
            model_name='router',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='router',
            name='upnp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='connecteddevice',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='router_manager.router'),
        ),
        migrations.AlterField(
            model_name='router',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='ssid',
            field=models.CharField(default='ConnectWise_Network', max_length=32),
        ),
        migrations.AlterField(
            model_name='router',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='router', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='connecteddevice',
            index=models.Index(fields=['router', 'last_seen'], name='router_mana_router__1ce8aa_idx'),
        ),
        migrations.AddIndex(
            model_name='connecteddevice',
            index=models.Index(fields=['mac_address'], name='router_mana_mac_add_3f63d1_idx'),
        ),
        migrations.AddField(
            model_name='routerlog',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='router_manager.router'),
        ),
        migrations.AddField(
            model_name='guestnetwork',
            name='router',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_network', to='router_manager.router'),
        ),
        migrations.AddIndex(
            model_name='routerlog',
            index=models.Index(fields=['router', 'created_at'], name='router_mana_router__2be64a_idx'),
        ),
    ]
